"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { MapPin, SlidersHorizontal, Star } from "lucide-react";
import { FilterChip, SearchBar, VetCard } from "@/components";
import { usePetcare } from "@/features/petcare-store";
import { formatInr, WorkspaceShell } from "@/features/workspace-shell";

export default function VeterinariansPage() {
  const router = useRouter(); const { vets } = usePetcare(); const [query,setQuery]=useState(""); const [specialization,setSpecialization]=useState("All"); const [rating,setRating]=useState(0); const [maxFee,setMaxFee]=useState(1200);
  const specializations=["All",...Array.from(new Set(vets.map((vet)=>vet.specialization)))]; const shown=useMemo(()=>vets.filter((vet)=>`${vet.name} ${vet.specialization} ${vet.clinic} ${vet.location}`.toLowerCase().includes(query.toLowerCase())&&(specialization==="All"||vet.specialization===specialization)&&vet.rating>=rating&&vet.fee<=maxFee),[vets,query,specialization,rating,maxFee]);
  return <WorkspaceShell title="Veterinarians" subtitle="Find care with transparent profiles, availability and fees."><div className="space-y-6"><section className="rounded-3xl bg-gradient-to-br from-sky via-white to-mint p-6 sm:p-8"><p className="eyebrow bg-white"><MapPin size={14}/> Pune care network</p><h2 className="mt-4 text-3xl font-black tracking-[-.04em] text-ink">Find the right kind of care.</h2><p className="mt-2 max-w-2xl text-slate-600">Search fictional demo clinicians by experience, specialization, availability and consultation fee.</p><SearchBar className="mt-6 max-w-2xl" value={query} onChange={setQuery} placeholder="Search name, specialty, clinic, or location"/></section><div className="surface p-4"><div className="flex flex-wrap items-center gap-2"><span className="inline-flex h-9 items-center gap-1.5 pr-1 text-sm font-bold text-slate-600"><SlidersHorizontal size={16}/>Filters</span>{specializations.map((item)=><FilterChip key={item} label={item} active={specialization===item} onClick={()=>setSpecialization(item)}/>)}</div><div className="mt-4 flex flex-wrap items-center gap-4 border-t border-slate-100 pt-4"><label className="flex items-center gap-2 text-sm font-semibold text-slate-600">Minimum rating <select className="field h-9 w-auto py-0" value={rating} onChange={(event)=>setRating(Number(event.target.value))}><option value={0}>Any rating</option><option value={4.7}>4.7+</option><option value={4.8}>4.8+</option></select></label><label className="flex items-center gap-2 text-sm font-semibold text-slate-600">Fee up to <select className="field h-9 w-auto py-0" value={maxFee} onChange={(event)=>setMaxFee(Number(event.target.value))}><option value={700}>{formatInr(700)}</option><option value={850}>{formatInr(850)}</option><option value={1200}>Any fee</option></select></label><p className="ml-auto text-sm text-slate-500">{shown.length} clinician{shown.length===1?"":"s"} found</p></div></div><div className="grid gap-4 lg:grid-cols-2">{shown.map((vet)=><VetCard key={vet.id} vet={{id:vet.id,name:vet.name,imageUrl:vet.image,specialization:vet.specialization,clinicName:vet.clinic,location:vet.location,rating:vet.rating,reviewCount:vet.reviews,yearsExperience:vet.experience,consultationFee:vet.fee,nextAvailable:`Today · ${vet.slots[0]}`}} href={`/veterinarians/${vet.id}`} onBook={()=>router.push(`/veterinarians/${vet.id}?book=1`)} />)}</div>{!shown.length&&<div className="surface p-12 text-center"><Star className="mx-auto text-moss"/><h2 className="mt-3 font-black text-ink">No veterinarians match those filters.</h2><button className="mt-4 btn-secondary" onClick={()=>{setQuery("");setSpecialization("All");setRating(0);setMaxFee(1200);}}>Reset filters</button></div>}</div></WorkspaceShell>;
}
