"use client";

import { FormEvent, useState } from "react";
import { CalendarCheck2, X } from "lucide-react";
import { ServiceProvider, Vet } from "@/features/demo-data";
import { usePetcare } from "@/features/petcare-store";

export function AppointmentBookingModal({ vet, onClose }: { vet: Vet; onClose: () => void }) {
  const { pets, bookAppointment } = usePetcare(); const [done, setDone] = useState(false); const [error, setError] = useState("");
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); if (!data.get("petId") || !data.get("date") || !data.get("time") || String(data.get("reason")).trim().length < 3) {setError("Select a pet, date, time, and reason.");return;} bookAppointment({petId:String(data.get("petId")),vetId:vet.id,date:String(data.get("date")),time:String(data.get("time")),type:data.get("type") as "In-person"|"Online",reason:String(data.get("reason")),notes:String(data.get("notes"))});setDone(true); }
  return <Modal title={`Book with ${vet.name}`} subtitle={`${vet.clinic} · ${new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(vet.fee)} consultation`} onClose={onClose}>{done ? <div className="py-8 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-mint text-moss"><CalendarCheck2 size={26}/></span><h3 className="mt-4 text-xl font-black text-ink">Request sent.</h3><p className="mt-2 text-sm leading-6 text-slate-600">Your appointment is pending confirmation. We created a reminder for the day before it.</p><button className="mt-6 btn-primary" onClick={onClose}>Done</button></div> : <form className="grid gap-5 sm:grid-cols-2" onSubmit={submit}><div><label className="field-label" htmlFor="appt-pet">Pet</label><select className="field" id="appt-pet" name="petId">{pets.map((pet)=><option key={pet.id} value={pet.id}>{pet.name} · {pet.species}</option>)}</select></div><div><label className="field-label" htmlFor="appt-type">Appointment type</label><select className="field" id="appt-type" name="type"><option>In-person</option><option>Online</option></select></div><div><label className="field-label" htmlFor="appt-date">Date</label><input className="field" id="appt-date" name="date" type="date" min="2026-08-26" defaultValue="2026-09-05" required/></div><div><label className="field-label" htmlFor="appt-time">Available time</label><select className="field" id="appt-time" name="time">{vet.slots.map((slot)=><option key={slot}>{slot}</option>)}</select></div><div className="sm:col-span-2"><label className="field-label" htmlFor="appt-reason">Reason for appointment</label><input className="field" id="appt-reason" name="reason" placeholder="e.g. Annual wellness visit" required/></div><div className="sm:col-span-2"><label className="field-label" htmlFor="appt-notes">Notes <span className="font-normal text-slate-400">(optional)</span></label><textarea className="field min-h-24 py-3" id="appt-notes" name="notes" placeholder="Anything the veterinarian should know before the visit?"/></div>{error && <p className="sm:col-span-2 rounded-xl bg-red-50 px-3 py-2 text-sm text-red-700" role="alert">{error}</p>}<div className="sm:col-span-2 flex justify-end gap-3 border-t border-slate-100 pt-5"><button className="btn-secondary" type="button" onClick={onClose}>Cancel</button><button className="btn-primary" type="submit">Request appointment</button></div></form>}</Modal>;
}

export function ServiceBookingModal({ provider, onClose }: { provider: ServiceProvider; onClose: () => void }) {
  const { pets, bookService } = usePetcare(); const [done,setDone]=useState(false); const [error,setError]=useState("");
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);if(!data.get("petId")||!data.get("date")||!data.get("time")){setError("Choose a pet, date and time.");return;}bookService({petId:String(data.get("petId")),providerId:provider.id,date:String(data.get("date")),time:String(data.get("time")),notes:String(data.get("notes"))});setDone(true);}
  return <Modal title={`Book ${provider.businessName}`} subtitle={`${provider.category} · from ${new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(provider.price)}`} onClose={onClose}>{done?<div className="py-8 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-mint text-moss"><CalendarCheck2 size={26}/></span><h3 className="mt-4 text-xl font-black text-ink">Booking request sent.</h3><p className="mt-2 text-sm leading-6 text-slate-600">The provider will review your preferred time. You can view it in your service history.</p><button className="mt-6 btn-primary" onClick={onClose}>Done</button></div>:<form className="grid gap-5 sm:grid-cols-2" onSubmit={submit}><div><label className="field-label" htmlFor="service-pet">Pet</label><select className="field" id="service-pet" name="petId">{pets.map((pet)=><option key={pet.id} value={pet.id}>{pet.name} · {pet.species}</option>)}</select></div><div><label className="field-label" htmlFor="service-date">Date</label><input className="field" id="service-date" name="date" type="date" min="2026-08-26" defaultValue="2026-09-04" required/></div><div><label className="field-label" htmlFor="service-time">Preferred time</label><select className="field" id="service-time" name="time">{provider.availability.map((slot)=><option key={slot}>{slot}</option>)}</select></div><div><label className="field-label" htmlFor="service-notes">Notes <span className="font-normal text-slate-400">(optional)</span></label><input className="field" id="service-notes" name="notes" placeholder="Care preferences"/></div>{error&&<p className="sm:col-span-2 rounded-xl bg-red-50 px-3 py-2 text-sm text-red-700" role="alert">{error}</p>}<div className="sm:col-span-2 flex justify-end gap-3 border-t border-slate-100 pt-5"><button className="btn-secondary" type="button" onClick={onClose}>Cancel</button><button className="btn-primary" type="submit">Request booking</button></div></form>}</Modal>;
}

function Modal({title,subtitle,onClose,children}:{title:string;subtitle:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[70] flex items-end bg-slate-950/45 sm:items-center sm:justify-center sm:p-6" role="dialog" aria-modal="true" aria-labelledby="booking-title"><button className="absolute inset-0" onClick={onClose} aria-label="Close booking form"/><div className="relative max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-t-3xl bg-white shadow-2xl sm:rounded-3xl"><div className="sticky top-0 z-10 flex items-start justify-between border-b border-slate-100 bg-white px-6 py-5"><div><h2 id="booking-title" className="text-xl font-black tracking-[-.03em] text-ink">{title}</h2><p className="mt-1 text-sm text-slate-600">{subtitle}</p></div><button className="grid h-9 w-9 place-items-center rounded-xl text-slate-500 hover:bg-slate-100" onClick={onClose} aria-label="Close"><X size={19}/></button></div><div className="p-6">{children}</div></div></div>}
