"use client";

import Link from "next/link";
import { PackageCheck, ShoppingBag, Truck } from "lucide-react";
import { Badge, EmptyState } from "@/components";
import { usePetcare } from "@/features/petcare-store";
import { formatDate, formatInr, WorkspaceShell } from "@/features/workspace-shell";

export default function OrdersPage(){const {orders,products}=usePetcare();return <WorkspaceShell title="Orders" subtitle="Marketplace order history and mock delivery status."><div className="space-y-4">{orders.length?orders.map((order)=>{const first=order.items[0]&&products.find((item)=>item.id===order.items[0].productId);return <article className="surface overflow-hidden" key={order.id}><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div><p className="font-black text-ink">{order.number}</p><p className="mt-1 text-sm text-slate-600">Placed {formatDate(order.date)} · {order.items.reduce((sum,item)=>sum+item.quantity,0)} item(s)</p></div><Badge tone={order.status==="DELIVERED"?"green":order.status==="CANCELLED"?"red":"teal"}>{order.status}</Badge></div><div className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><img className="h-16 w-16 rounded-2xl object-cover" src={first?.image} alt="Ordered product"/><div className="min-w-0 flex-1"><p className="font-bold text-ink">{first?.name??"Marketplace order"}{order.items.length>1?` + ${order.items.length-1} more`:""}</p><p className="mt-1 text-sm text-slate-600">Delivery to {order.address}</p></div><p className="font-black text-ink">{formatInr(order.total)}</p></div><div className="grid grid-cols-3 border-t border-slate-100 text-center text-xs font-bold"><span className="flex flex-col items-center gap-1 py-3 text-moss"><PackageCheck size={16}/>Placed</span><span className={`flex flex-col items-center gap-1 py-3 ${["SHIPPED","DELIVERED"].includes(order.status)?"text-moss":"text-slate-400"}`}><Truck size={16}/>Shipped</span><span className={`flex flex-col items-center gap-1 py-3 ${order.status==="DELIVERED"?"text-moss":"text-slate-400"}`}><ShoppingBag size={16}/>Delivered</span></div></article>}):<EmptyState title="No marketplace orders yet." description="When you complete a mock checkout, your orders will appear here." action={<Link href="/marketplace" className="btn-primary">Browse marketplace</Link>}/>}</div></WorkspaceShell>}
