import { NextRequest } from "next/server";
import { apiError, body, ok, requireApiActor } from "@/lib/api-helpers";
import { requirePetReadAccess } from "@/lib/authorization";
import { getRepository } from "@/lib/repository";
import { aiMessageSchema } from "@/lib/validation";

const disclaimer="PetCare AI provides general information and is not a substitute for professional veterinary care.";
function reply(message:string,petName:string,nextVaccine?:string){const lower=message.toLowerCase();if(/breath|collapse|seizure|poison|unable to urinate|repeated vomiting/.test(lower))return {content:`This may need urgent professional care. Please contact a veterinarian or emergency veterinary service now. I cannot diagnose the cause. ${disclaimer}`,urgent:true};if(lower.includes("vaccin"))return {content:nextVaccine?`${petName}'s next recorded vaccination is due ${nextVaccine}. Please ask the veterinarian to confirm the schedule. ${disclaimer}`:`I cannot find an upcoming vaccination in the available record. A veterinarian can review the record with you. ${disclaimer}`,urgent:false};if(/scratch|itch|pain|symptom/.test(lower))return {content:`I’m sorry ${petName} is uncomfortable. I can’t diagnose the cause or prescribe treatment. Note when it started, whether it is worsening, appetite/energy changes and any new products, then contact a veterinarian for clinical advice. ${disclaimer}`,urgent:false};return {content:`I can help explain available records and prepare questions for a veterinarian. Could you share when this started, whether it is changing, and how ${petName}'s appetite, energy and bathroom habits are? ${disclaimer}`,urgent:false};}
export async function GET(request:NextRequest){try{const actor=requireApiActor(request);const petId=request.nextUrl.searchParams.get("petId")??undefined;return ok(getRepository().listConversations(actor.id,petId));}catch(error){return apiError(error);}}
export async function POST(request:NextRequest){try{const actor=requireApiActor(request);const input=aiMessageSchema.parse(await body(request));const repository=getRepository();const state=repository.snapshot();const pet=state.pets.find((item)=>item.id===input.petId);requirePetReadAccess(actor,pet,state);const vaccine=state.vaccinations.filter((item)=>item.petId===input.petId&&item.nextDueDate).sort((a,b)=>(a.nextDueDate??"").localeCompare(b.nextDueDate??""))[0];const result=reply(input.message,pet.name,vaccine?.nextDueDate);return ok({...result,disclaimer,followUpQuestions:["When did you first notice this?","Has appetite or energy changed?","What would you like to ask the veterinarian?"]});}catch(error){return apiError(error);}}
