import { NextRequest } from "next/server";
import { apiError, body, ok, requireApiActor } from "@/lib/api-helpers";
import { canWritePet, isAdministrator } from "@/lib/authorization";
import { createId, getRepository, nowIso } from "@/lib/repository";
import { z } from "zod";

const bookingSchema=z.object({petId:z.string().min(1),serviceId:z.string().min(1),providerId:z.string().min(1),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),time:z.string().regex(/^\d{2}:\d{2}$/),notes:z.string().max(2000).optional()});
export async function GET(request:NextRequest){try{const actor=requireApiActor(request);const repository=getRepository();const rows=repository.listServiceBookings().filter((booking)=>isAdministrator(actor)||booking.ownerId===actor.id||repository.listServiceProviders().some((provider)=>provider.id===booking.providerId&&provider.userId===actor.id));return ok(rows);}catch(error){return apiError(error);}}
export async function POST(request:NextRequest){try{const actor=requireApiActor(request);const input=bookingSchema.parse(await body(request));const repository=getRepository();const value=repository.transaction((draft)=>{const pet=draft.pets.find((item)=>item.id===input.petId);if(!pet||!canWritePet(actor,pet))throw Object.assign(new Error("You can only book a service for your own pet."),{statusCode:pet?403:404});if(!draft.services.some((item)=>item.id===input.serviceId)||!draft.serviceProviders.some((item)=>item.id===input.providerId))throw Object.assign(new Error("Service provider not found."),{statusCode:404});const entry={id:createId("booking"),ownerId:actor.id,...input,status:"PENDING" as const,createdAt:nowIso(),updatedAt:nowIso()};draft.serviceBookings.push(entry);return entry;});return ok(value,{status:201});}catch(error){return apiError(error);}}
export async function PATCH(request:NextRequest){try{const actor=requireApiActor(request);const payload=await body<{id:string;status:"CONFIRMED"|"COMPLETED"|"CANCELLED"}> (request);const repository=getRepository();const value=repository.transaction((draft)=>{const booking=draft.serviceBookings.find((item)=>item.id===payload.id);if(!booking)throw Object.assign(new Error("Booking not found."),{statusCode:404});const provider=draft.serviceProviders.find((item)=>item.id===booking.providerId);if(!isAdministrator(actor)&&booking.ownerId!==actor.id&&provider?.userId!==actor.id)throw Object.assign(new Error("You cannot update this booking."),{statusCode:403});booking.status=payload.status;booking.updatedAt=nowIso();return booking;});return ok(value);}catch(error){return apiError(error);}}
