"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Bot, CalendarPlus, CheckCircle2, ClipboardPlus, HeartPulse, PawPrint, QrCode, ShieldAlert, ShoppingBag, Sparkles, Stethoscope, Watch } from "lucide-react";
import { AppointmentCard, DashboardCard, DigitalTwinFlow, HealthTimeline, NextBestActions, PetCareReadinessCard, PetCard, PetInsightsPanel, ProductCard, ReminderCard, SectionHeading } from "@/components";
import { usePetcare } from "@/features/petcare-store";
import { formatPetAge, WorkspaceShell } from "@/features/workspace-shell";
import { buildPetContext, calculatePetCareReadiness, generatePetInsights, getNextBestActions, getPetProductRecommendations } from "@/lib/pet-digital-twin";

export default function DashboardPage() {
  const { user, pets, records, vaccinations, medications, weights, reminders, appointments, orders, bookings, vets, providers, products, bands, bandMetrics, habits, bandAlerts, locationPoints, memories, documents, insightOutcomes, addToCart } = usePetcare();
  const [activePetId, setActivePetId] = useState("");
  useEffect(() => {
    if (!pets.some((pet) => pet.id === activePetId)) setActivePetId(pets[0]?.id ?? "");
  }, [activePetId, pets]);
  const primaryPet = pets.find((pet) => pet.id === activePetId) ?? pets[0];
  const petContext = useMemo(() => primaryPet ? buildPetContext({
    pet: primaryPet, records, vaccinations, medications, weights, reminders, appointments, orders, bookings, providers, vets, bands, bandMetrics, habits, bandAlerts, locationPoints, memories, documents, insightOutcomes, products,
  }) : undefined, [primaryPet, records, vaccinations, medications, weights, reminders, appointments, orders, bookings, providers, vets, bands, bandMetrics, habits, bandAlerts, locationPoints, memories, documents, insightOutcomes, products]);
  const petInsights = useMemo(() => petContext ? generatePetInsights(petContext) : [], [petContext]);
  const careReadiness = useMemo(() => petContext ? calculatePetCareReadiness(petContext) : undefined, [petContext]);
  const nextActions = useMemo(() => getNextBestActions(petInsights, 3), [petInsights]);
  const pending = reminders.filter((item) => item.status !== "DONE").sort((left, right) => `${left.date}${left.time}`.localeCompare(`${right.date}${right.time}`));
  const upcoming = appointments.filter((item) => item.status === "PENDING" || item.status === "CONFIRMED").sort((left, right) => `${left.date}${left.time}`.localeCompare(`${right.date}${right.time}`));
  const events = [
    ...records.map((record) => ({ id: `record-${record.id}`, date: record.date, title: record.reason, description: record.diagnosis, type: record.type === "Consultation" ? "visit" as const : "record" as const, meta: `${record.veterinarian} · ${record.clinic}` })),
    ...pending.slice(0, 2).map((reminder) => ({ id: `reminder-${reminder.id}`, date: reminder.date, title: reminder.title, description: reminder.description, type: "reminder" as const })),
  ].sort((left, right) => right.date.localeCompare(left.date)).slice(0, 5);
  const recommended = useMemo(() => petContext
    ? getPetProductRecommendations(petContext, products).map(({ product, reason }) => ({ ...product, reason }))
    : products.slice(0, 3), [petContext, products]);
  const firstName = user.name.trim().split(/\s+/)[0] || "there";

  return (
    <WorkspaceShell title="Dashboard" subtitle="A calm, connected view of every care detail." actions={<Link href={pets.length ? "/pets" : "/onboarding"} className="hidden btn-primary sm:inline-flex"><PawPrint size={16} /> {pets.length ? "Add pet" : "Create pet passport"}</Link>}>
      <div className="space-y-7">
        <section className="overflow-hidden rounded-3xl bg-ink p-6 text-white shadow-lift sm:p-8"><div className="relative"><div className="pointer-events-none absolute -right-24 -top-32 h-72 w-72 rounded-full bg-moss/60 blur-3xl" /><div className="relative flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><div><p className="text-sm font-bold text-[#a7ded2]">PETCARE HUB · TODAY</p><h1 className="mt-2 text-3xl font-black tracking-[-.04em] sm:text-4xl">Good evening, {firstName}.</h1><p className="mt-3 max-w-xl leading-7 text-slate-300">{primaryPet ? `Everything for ${primaryPet.name} and your other companions is connected here: their passport, care plan and next useful task.` : "Create your first pet passport to connect health history, wearable context, care plans and trusted services in one place."}</p></div><div className="flex flex-wrap gap-2"><Link href="/passport" className="btn-secondary border-white/10 bg-white/10 text-white hover:bg-white hover:text-ink"><QrCode size={16} /> Open passport</Link><Link href="/ai-assistant" className="btn-secondary border-white/10 bg-white/10 text-white hover:bg-white hover:text-ink"><Bot size={16} /> Ask PetCare AI</Link></div></div></div></section>

        {primaryPet && petContext && careReadiness ? <>
          <section className="surface flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow"><Sparkles size={14} /> Pet-centred workspace</p><p className="mt-1 text-sm text-slate-600">Choose the pet whose digital twin drives this dashboard.</p></div><label className="min-w-[12rem]"><span className="sr-only">Active pet</span><select className="field" value={primaryPet.id} onChange={(event) => setActivePetId(event.target.value)}>{pets.map((pet) => <option value={pet.id} key={pet.id}>{pet.name} · {pet.species}</option>)}</select></label></section>
          <DigitalTwinFlow petName={primaryPet.name} />
          <section className="grid gap-6 xl:grid-cols-[1.08fr_.92fr]"><PetCareReadinessCard readiness={careReadiness} /><NextBestActions actions={nextActions} /></section>
          <PetInsightsPanel insights={petInsights} limit={2} />
        </> : null}

        <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><DashboardCard label="Your pets" value={pets.length} description="Profiles in your care" icon={PawPrint} accent="teal" /><DashboardCard label="Care reminders" value={pending.length} description="A few small things ahead" icon={HeartPulse} accent="orange" /><DashboardCard label="Upcoming visits" value={upcoming.length} description="Vet care already planned" icon={CalendarPlus} accent="sky" /><DashboardCard label="Health activity" value={records.length} description="Records in your timeline" icon={ClipboardPlus} accent="violet" /><DashboardCard label="Band insights" value={bandAlerts.filter((alert) => alert.status === "OPEN").length} description={bands.some((band) => band.status === "CONNECTED") ? "Wearable trends to review" : "Connect a tracker"} icon={Watch} accent="teal" /></section>

        <section><SectionHeading title="Your pets" description="Their profiles are the centre of every care decision." action={<Link className="btn-ghost" href="/pets">Manage pets <ArrowRight size={15} /></Link>} /><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{pets.map((pet) => <PetCard key={pet.id} href={`/pets/${pet.id}`} pet={{ id: pet.id, name: pet.name, species: pet.species, breed: pet.breed, age: formatPetAge(pet.birthDate), weight: pet.weight, imageUrl: pet.image, healthStatus: pet.vaccinationStatus === "Overdue" ? "overdue" : pet.vaccinationStatus === "Due soon" ? "attention" : "good", nextCare: pending.find((reminder) => reminder.petId === pet.id)?.title ?? "No care due soon" }} />)}<Link href={pets.length ? "/pets" : "/onboarding"} className="flex min-h-48 flex-col items-center justify-center rounded-2xl border border-dashed border-moss/30 bg-mint/40 p-5 text-center transition hover:bg-mint"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-white text-moss shadow-sm"><PawPrint size={21} /></span><span className="mt-3 font-bold text-ink">{pets.length ? "Add another pet" : "Create your first passport"}</span><span className="mt-1 text-sm text-slate-600">{pets.length ? "Keep every companion close." : "Start with the pet at the centre."}</span></Link></div></section>

        <section className="grid gap-6 xl:grid-cols-[1.12fr_.88fr]"><div><SectionHeading title="Upcoming care" description="The next helpful things, in order." action={<Link className="btn-ghost" href="/calendar">Care calendar <ArrowRight size={15} /></Link>} /><div className="mt-4 space-y-3">{pending.slice(0, 4).map((reminder) => { const pet = pets.find((item) => item.id === reminder.petId); return <ReminderCard key={reminder.id} reminder={{ id: reminder.id, title: reminder.title, description: reminder.description, petName: pet?.name ?? "Your pet", dueDate: reminder.date, dueTime: reminder.time, type: reminder.type, status: reminder.status === "DONE" ? "COMPLETED" : "UPCOMING", recurring: reminder.recurring }} href="/reminders" />; })}{!pending.length ? <div className="surface p-8 text-center"><CheckCircle2 className="mx-auto text-moss" /><p className="mt-3 font-bold text-ink">All caught up.</p><p className="mt-1 text-sm text-slate-600">There are no open reminders right now.</p></div> : null}</div></div><div><SectionHeading title="Next appointments" description="Your upcoming vet care." action={<Link className="btn-ghost" href="/appointments">All appointments <ArrowRight size={15} /></Link>} /><div className="mt-4 space-y-3">{upcoming.slice(0, 3).map((appointment) => { const pet = pets.find((item) => item.id === appointment.petId); const vet = vets.find((item) => item.id === appointment.vetId); return <AppointmentCard key={appointment.id} href="/appointments" appointment={{ id: appointment.id, petName: pet?.name ?? "Your pet", veterinarianName: vet?.name ?? "Veterinarian", clinicName: vet?.clinic, date: appointment.date, time: appointment.time, type: appointment.type === "In-person" ? "IN_PERSON" : "ONLINE", status: appointment.status, reason: appointment.reason, veterinarianImageUrl: vet?.image }} />; })}{!upcoming.length ? <div className="surface p-8 text-center"><CalendarPlus className="mx-auto text-moss" /><p className="mt-3 font-bold text-ink">No appointments booked.</p><Link href="/veterinarians" className="btn-primary mt-3">Find a veterinarian</Link></div> : null}</div></div></section>

        <section className="grid gap-6 xl:grid-cols-[1.12fr_.88fr]"><HealthTimeline events={events} title="Recent health activity" description="A chronological picture of care, not a pile of files." action={<Link href="/health" className="btn-ghost">Open health <ArrowRight size={15} /></Link>} /><div className="surface overflow-hidden bg-gradient-to-br from-mint to-white p-6"><p className="text-xs font-bold uppercase tracking-[.14em] text-moss">Quick actions</p><h2 className="mt-2 text-xl font-black tracking-[-.03em] text-ink">What would help today?</h2><div className="mt-5 grid gap-2 sm:grid-cols-2 xl:grid-cols-1">{[{ href: "/passport", label: "Open digital passport", icon: QrCode }, { href: "/health", label: "Add health record", icon: ClipboardPlus }, { href: "/calendar", label: "Review care calendar", icon: CalendarPlus }, { href: "/health-band", label: "Review Health Band", icon: Watch }, { href: "/veterinarians", label: "Book a vet", icon: Stethoscope }, { href: "/emergency", label: "Emergency handoff", icon: ShieldAlert }, { href: "/ai-assistant", label: "Ask PetCare AI", icon: Bot }].map(({ href, label, icon: Icon }) => <Link key={href} href={href} className="flex items-center gap-3 rounded-xl bg-white p-3 text-sm font-bold text-ink shadow-sm transition hover:-translate-y-0.5 hover:text-moss"><span className="grid h-9 w-9 place-items-center rounded-xl bg-mint text-moss"><Icon size={17} /></span>{label}<ArrowRight className="ml-auto text-slate-400" size={16} /></Link>)}</div></div></section>

        <section><SectionHeading eyebrow="Personalized marketplace" title={primaryPet ? `Recommended for ${primaryPet.name}` : "Profile-aware essentials"} description={primaryPet ? "Non-prescription essentials matched to the first pet in your workspace." : "Create a pet profile for tailored recommendations."} action={<Link href="/marketplace" className="btn-ghost">See marketplace <ArrowRight size={15} /></Link>} /><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{recommended.map((product) => <ProductCard key={product.id} product={{ id: product.id, name: product.name, brand: product.brand, imageUrl: product.image, price: product.price, originalPrice: product.originalPrice, rating: product.rating, reviewCount: product.reviews, category: product.category, stock: product.stock, recommendationReason: primaryPet ? `Matches ${primaryPet.name}’s ${primaryPet.species.toLowerCase()} profile` : product.reason }} href={`/marketplace/${product.id}`} onAddToCart={() => addToCart(product.id)} />)}</div><p className="mt-4 text-xs text-slate-500">Recommendations are rule-based and informational. Review ingredients against your pet’s profile; PetCare Hub does not recommend prescription medicines.</p></section>
      </div>
    </WorkspaceShell>
  );
}
