"use client";

import Link from "next/link";
import { BellRing, CalendarDays, CheckCircle2, Clock3, Stethoscope } from "lucide-react";
import { usePetcare } from "@/features/petcare-store";
import { formatDate, WorkspaceShell } from "@/features/workspace-shell";

type CalendarEvent = { id: string; date: string; time?: string; title: string; detail: string; petName: string; kind: "reminder" | "appointment"; completed?: boolean };

export default function CareCalendarPage() {
  const { pets, reminders, appointments } = usePetcare();
  const events: CalendarEvent[] = [
    ...reminders.map((reminder) => ({ id: `reminder-${reminder.id}`, date: reminder.date, time: reminder.time, title: reminder.title, detail: reminder.description, petName: pets.find((pet) => pet.id === reminder.petId)?.name ?? "Your pet", kind: "reminder" as const, completed: reminder.status === "DONE" })),
    ...appointments.map((appointment) => ({ id: `appointment-${appointment.id}`, date: appointment.date, time: appointment.time, title: appointment.reason, detail: `${appointment.type} veterinary appointment · ${appointment.status.toLowerCase()}`, petName: pets.find((pet) => pet.id === appointment.petId)?.name ?? "Your pet", kind: "appointment" as const, completed: appointment.status === "COMPLETED" || appointment.status === "CANCELLED" })),
  ].sort((left, right) => `${left.date}${left.time ?? ""}`.localeCompare(`${right.date}${right.time ?? ""}`));
  const grouped = events.reduce<Record<string, CalendarEvent[]>>((output, event) => ({ ...output, [event.date]: [...(output[event.date] ?? []), event] }), {});
  const openCount = events.filter((event) => !event.completed).length;

  return (
    <WorkspaceShell title="Pet-care calendar" subtitle="Health, wellbeing and everyday care in a single rhythm." actions={<Link href="/reminders" className="btn-primary"><BellRing size={16} /> Add reminder</Link>}>
      <div className="space-y-6">
        <section className="rounded-3xl bg-gradient-to-br from-mint via-white to-sky p-6 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><span className="eyebrow bg-white"><CalendarDays size={14} /> Connected care plan</span><h1 className="mt-4 text-3xl font-black tracking-[-.04em] text-ink">Everything due for every pet.</h1><p className="mt-2 max-w-2xl text-slate-600">Appointments, vaccinations, medication, grooming and custom tasks are pulled from the same profile data—not separate to-do lists.</p></div><div className="rounded-2xl bg-white p-4 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Open care items</p><p className="mt-1 text-3xl font-black text-ink">{openCount}</p></div></div></section>
        <section className="grid gap-4 sm:grid-cols-3"><article className="surface p-5"><Clock3 className="text-moss" size={20} /><p className="mt-3 text-sm font-bold text-slate-500">Upcoming reminders</p><p className="mt-1 text-2xl font-black text-ink">{reminders.filter((item) => item.status !== "DONE").length}</p></article><article className="surface p-5"><Stethoscope className="text-moss" size={20} /><p className="mt-3 text-sm font-bold text-slate-500">Vet appointments</p><p className="mt-1 text-2xl font-black text-ink">{appointments.filter((item) => ["PENDING", "CONFIRMED"].includes(item.status)).length}</p></article><article className="surface p-5"><CheckCircle2 className="text-moss" size={20} /><p className="mt-3 text-sm font-bold text-slate-500">Pets in plan</p><p className="mt-1 text-2xl font-black text-ink">{new Set(events.map((event) => event.petName)).size}</p></article></section>
        <section className="surface p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-black tracking-[-.03em] text-ink">Care schedule</h2><p className="mt-1 text-sm text-slate-600">Complete tasks on Reminders and manage bookings on Appointments.</p></div><div className="flex gap-2"><Link href="/appointments" className="btn-secondary">Appointments</Link><Link href="/reminders" className="btn-secondary">Reminders</Link></div></div><div className="mt-6 space-y-7">{Object.entries(grouped).map(([date, dateEvents]) => <div key={date}><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-mint text-center text-xs font-black text-moss">{new Date(`${date}T12:00:00`).toLocaleDateString("en-IN", { day: "numeric", month: "short" })}</span><div><p className="font-black text-ink">{formatDate(date, { weekday: "long", day: "numeric", month: "long" })}</p><p className="text-xs text-slate-500">{dateEvents.length} care item{dateEvents.length === 1 ? "" : "s"}</p></div></div><div className="ml-5 mt-3 space-y-3 border-l-2 border-mint/60 pl-6">{dateEvents.map((event) => <article key={event.id} className={`rounded-2xl border p-4 ${event.completed ? "border-slate-100 bg-slate-50 text-slate-500" : "border-slate-100 bg-white shadow-sm"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><span className={`grid h-9 w-9 place-items-center rounded-xl ${event.kind === "appointment" ? "bg-sky text-sky-900" : "bg-mint text-moss"}`}>{event.kind === "appointment" ? <Stethoscope size={17} /> : <BellRing size={17} />}</span><div><p className="font-bold text-ink">{event.title}</p><p className="mt-1 text-sm text-slate-600">{event.petName} · {event.detail}</p></div></div><div className="text-right text-sm font-bold text-slate-500">{event.time || "All day"}{event.completed ? <p className="mt-1 text-xs text-moss">Completed</p> : null}</div></div></article>)}</div></div>)}{!events.length ? <div className="rounded-2xl bg-slate-50 p-10 text-center"><CalendarDays className="mx-auto text-moss" /><h3 className="mt-3 font-black text-ink">Your care calendar is ready.</h3><p className="mt-2 text-sm text-slate-600">Add a reminder or book an appointment to begin building a connected care plan.</p></div> : null}</div></section>
      </div>
    </WorkspaceShell>
  );
}
